sudo: required
services:
  - docker

before_install:
  - docker build -t chaitanyapsrk/docker-react -f Dockerfile.dev .

scripts:
  - docker run -e CI=true chaitanyapsrk/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker"
  env: "Docker-env"
  bucket-name: "elasticbeanstalk-us-east-1-038019714415"
  bucket-path: "docker"
  on:
   branch: master
   access_key_id: "$AWS_ACCESS_KEY"
   secret_access_key: "$AWS_SECRET_KEY"